### ISSUE TITLE
Replace block with suspend in keywords

### ISSUE THREAD

**Issue by ankitdbst** [saurabhere/BugMeLater#11]
> Your description should contain certain keywords you’re targeting with your app. Say you have a camera app named “Funky Camera Tricks”. Use the word ‘camera’ 3-6 times in your app description, (while keeping it relevant) and also use the words ‘tricks’ and ‘funky’ a few times.
> 
> Go on the normal Adwords Keyword Tool and search for lateral keywords to use as well. Using lateral keywords (the ones suggested by Google after you’ve done your main search) will improve your app’s chance to get into the search results for those main keywords. You want to create a Goldilocks description: not too much keyword usage, not too long or too short. Keep it balanced.

Taking inspiration. ;)

I think we should use Suspend instead of Block in our settings activity (to match with app description) to better convey the overall theme. We don't _block_, we _suspend_. It will be easier to understand.
WDYT?

**Comment by saurabhere** [comment]
Agree
