### ISSUE TITLE
Replace getSharedPreferences calls with storage in static/private variable

### ISSUE THREAD

**Issue by ankitdbst** [saurabhere/BugMeLater#12]
https://developer.android.com/reference/android/content/Context.html#getSharedPreferences(java.lang.String, int)
Returns a reference (that is why we can make edits), and is thread-safe.

**Comment by saurabhere** [comment]
I think it is already implemented that way.

**Comment by ankitdbst** [comment]
I was talking about multiple calls to `getSharedPreferences`.
