### ISSUE TITLE
Show all button

### ISSUE THREAD

**Issue by ankitdbst** [saurabhere/BugMeLater#2]
I think show all can be simplified. I can add a more descriptive text to tell the user to disable the preferences to see his notification instantly.

I think that it conveys the intention more intuitively. 
- If he has _interruptions_ or _work hours_ set then disabling either should show notifications instantly
- If he has both set then:
   - if he is out of _work hours_ and turns off _interruptions_ we should show all
   - if he does not have any _interruptions_ set (None) then turning off _work hours_ (assuming he is in _work hours_) should show all
   - otherwise he should disable both

WDYT?

P.S Changing the interruptions filter allowed to: Priority/Alarms/None. All conveys that no filter is set

**Comment by saurabhere** [comment]
I think an explicit "show all" is required. A new user who doesn't understand our notification blocking system and just wants their notifications back right now would feel frustrated otherwise.

**Comment by ankitdbst** [comment]
![screenshot_1482069590](https://cloud.githubusercontent.com/assets/1544263/21293965/744eb9aa-c558-11e6-8a55-e9d3365a89f0.png)
Agree that the user may feel frustrated, if he doesn't understand the blocking of notifications. But my reasons for not having the button is:
1. When we choose DND, we know intuitively that clicking it again will make us come out of it. So i believe it is easier for user to understand that as a toggle switch
2. On the implementation level, Android doesn't guarantee showing the text (on the action bar) although i tried `showAsAction=always|withText`; which means with an icon only we have to convey that such a button allows-you-to-view-all-your-pending-notification-buffered-by-our-app

**Comment by ankitdbst** [comment]
Added the icon as we discussed.
