### ISSUE TITLE
Support for selecting a list of apps to trigger on.

### ISSUE THREAD

**Issue by saurabhere** [saurabhere/BugMeLater#6]

**Comment by ankitdbst** [comment]
Service wasn't running for me. So couldn't wire the preference `Set<String>` `excludeApps` to the service

**Comment by saurabhere** [comment]
A noob's(my) way would be to send an intent to the service and have it
populate/update its own Set.

**Comment by ankitdbst** [comment]
`MyNotificationListener` already reads from the perference, it needs to read the same preference `excludeApps`. What I meant is that for me the Listener Service is not running like yesterday. Need to look more into it.
